"""
app/models.py
=============
SQLAlchemy 2.x ORM models for EduPath AI Career Counsellor.

Eight tables, exactly matching the production database design:

  1. User                  — accounts and identity
  2. Session               — one interview run per row
  3. StudentProfile        — all 21 interview-step fields
  4. SubjectPerformance    — one row per subject per profile  (step 5)
  5. InterestRating        — one row per interest field per profile  (step 9)
  6. CommunicationSkill    — one row per skill per profile  (step 12)
  7. Report                — each AI-generated report output
  8. ReportSection         — each individual section within a report

Rules applied throughout:
  • All primary keys are UUID, generated by the database via gen_random_uuid().
  • All datetime columns are TIMESTAMPTZ (timezone-aware).
  • server_default=func.now() is used on audit timestamps so the DB sets them,
    not the application — removes clock-skew risk.
  • onupdate=func.now() keeps updated_at current on every UPDATE.
  • JSONB (PostgreSQL-native) for array/dict fields that are always read and
    written as a unit and are never queried column-by-column.
  • Individually queried data (marks, ratings, skills) gets its own child table.
  • All rating/score columns carry DB-level CHECK constraints (1–10) as a last
    line of defence after Pydantic has already validated the API input.
  • Relationships are declared on both sides with back_populates so SQLAlchemy
    keeps both ends of the object graph in sync.
  • cascade="all, delete-orphan" on child relationships so deleting a parent
    row automatically removes its children without manual cleanup.
  • passive_deletes=True tells SQLAlchemy to let PostgreSQL handle the actual
    DELETE cascade via the FK constraint, which is more efficient.

Do NOT import this module directly from routers or business logic.
Route handlers obtain models through the session returned by get_db().
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


# ---------------------------------------------------------------------------
# 1. USER
#
# Purpose:
#   Authentication and identity layer.  The current codebase has no auth —
#   this table introduces proper user accounts so sessions can be resumed
#   across devices and reports accessed securely.
#
# Note on hashed_password:
#   Nullable so OAuth-only accounts (Google, GitHub) can exist without a
#   password.  When adding auth, use passlib[bcrypt] — never store plaintext.
# ---------------------------------------------------------------------------

class User(Base):
    __tablename__ = "users"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Surrogate PK — never expose sequential IDs in public APIs",
    )

    # -- Identity ------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(320),
        nullable=False,
        unique=True,
        index=True,
        comment="Login key — RFC 5321 max length is 320 chars",
    )
    hashed_password: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="bcrypt hash; NULL for OAuth-only accounts",
    )
    full_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )

    # -- Role & status -------------------------------------------------------
    role: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        server_default="student",
        comment="student | counsellor | admin",
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="true",
        comment="Soft-disable without deletion",
    )
    is_verified: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
        comment="Email verification gate",
    )

    # -- Audit timestamps ----------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    last_login_at: Mapped[Optional[datetime]] = mapped_column(
        nullable=True,
        comment="Updated on successful authentication",
    )

    # -- Relationships -------------------------------------------------------
    sessions: Mapped[List["Session"]] = relationship(
        "Session",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    reports: Mapped[List["Report"]] = relationship(
        "Report",
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r} role={self.role!r}>"


# ---------------------------------------------------------------------------
# 2. SESSION
#
# Purpose:
#   One row per interview run.  Replaces the single sessions.json file.
#   A user can have many sessions (abandoned runs, annual re-counselling).
#   Anonymous (guest) sessions are allowed: user_id is nullable.
#
# session_code:
#   Preserves the existing SES001 / SES002 format from storage.py so
#   existing API consumers require no changes.  Backed by a PostgreSQL
#   sequence instead of the current in-memory counter (which resets on
#   server restart).
# ---------------------------------------------------------------------------

class Session(Base):
    __tablename__ = "sessions"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Human-readable code (API-facing) ------------------------------------
    session_code: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        unique=True,
        index=True,
        comment="SES001 format; unique; used in all existing API URLs",
    )

    # -- Ownership -----------------------------------------------------------
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="NULL = anonymous / guest session",
    )

    # -- Interview progress --------------------------------------------------
    current_step: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        server_default="1",
        comment="1–21; incremented by each /steps/* endpoint",
    )
    steps_completed: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        comment="Ordered list of step numbers that have been submitted",
    )
    collection_complete: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
        comment="Set true after step 21 is submitted",
    )
    report_generated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
    )

    # -- Lifecycle -----------------------------------------------------------
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        server_default="active",
        index=True,
        comment="active | completed | abandoned | expired",
    )

    # -- Audit timestamps ----------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
        index=True,
        comment="Indexed for session history sorted by recency",
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        nullable=True,
        index=True,
        comment="TTL; cleanup job deletes rows where expires_at < now()",
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "current_step >= 1 AND current_step <= 21",
            name="ck_sessions_current_step_range",
        ),
        CheckConstraint(
            "status IN ('active', 'completed', 'abandoned', 'expired')",
            name="ck_sessions_status_values",
        ),
    )

    # -- Relationships -------------------------------------------------------
    user: Mapped[Optional["User"]] = relationship(
        "User",
        back_populates="sessions",
    )
    profile: Mapped[Optional["StudentProfile"]] = relationship(
        "StudentProfile",
        back_populates="session",
        uselist=False,                          # one-to-one
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    reports: Mapped[List["Report"]] = relationship(
        "Report",
        back_populates="session",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return (
            f"<Session code={self.session_code!r} "
            f"step={self.current_step} "
            f"complete={self.collection_complete}>"
        )


# ---------------------------------------------------------------------------
# 3. STUDENT PROFILE
#
# Purpose:
#   Core domain table.  Stores every field collected across all 21 interview
#   steps.  Direct structural equivalent of create_empty_profile() in
#   storage.py, now properly typed and enforced at the database level.
#
# JSONB vs child tables:
#   Fields that are always read/written as a unit and never queried
#   individually (secondary_subjects, higher_subjects, hobbies, games, etc.)
#   remain JSONB.  Fields that ARE queried individually for analytics
#   (subject marks, interest ratings, communication scores) get child tables.
#
# Nullable policy:
#   All profile data columns are nullable by design — they are populated
#   progressively as the student completes each interview step.  Requiring
#   NOT NULL here would prevent saving partial profiles, breaking the
#   step-by-step UX.
# ---------------------------------------------------------------------------

class StudentProfile(Base):
    __tablename__ = "student_profiles"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign keys --------------------------------------------------------
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,                            # enforces one-to-one with Session
        index=True,
        comment="One profile per session — UNIQUE FK enforces 1:1",
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Denormalized for fast user-profile lookup without joining Session",
    )

    # ── Step 2: Personal Information ─────────────────────────────────────────
    name: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    age: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        nullable=True,
        comment="Validated 10–60 by Pydantic; CHECK enforces at DB level",
    )
    gender: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    country: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    native_language: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    education_language: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # ── Step 3: Secondary Education ──────────────────────────────────────────
    secondary_system: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True,
        comment="Matric | O-Level | Other",
    )
    secondary_year: Mapped[Optional[int]] = mapped_column(SmallInteger, nullable=True)
    secondary_subjects: Mapped[Optional[list]] = mapped_column(
        JSONB, nullable=True,
        comment='e.g. ["Math", "Physics", "Chemistry"]',
    )
    secondary_marks: Mapped[Optional[float]] = mapped_column(
        Numeric(5, 2), nullable=True,
        comment="0.00–100.00",
    )
    secondary_grade: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    secondary_completed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)

    # ── Step 4: Higher Education ─────────────────────────────────────────────
    higher_system: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True,
        comment="FSc | A-Level | Other",
    )
    higher_year: Mapped[Optional[int]] = mapped_column(SmallInteger, nullable=True)
    higher_subjects: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)
    higher_subject_marks: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True,
        comment='e.g. {"Computer Science": "95%", "Math": "90%"}',
    )
    higher_completed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)

    # ── Step 6: Favourite Subject ─────────────────────────────────────────────
    favourite_subject: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    favourite_topics: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 7: Career Decision ───────────────────────────────────────────────
    current_degree_plan: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Step 8: Preferred Countries ───────────────────────────────────────────
    study_country: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    work_country: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # ── Step 10: Programming Assessment ──────────────────────────────────────
    has_programmed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    programming_languages: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)
    programming_interest: Mapped[Optional[int]] = mapped_column(SmallInteger, nullable=True)
    programming_experience: Mapped[Optional[int]] = mapped_column(
        SmallInteger, nullable=True,
        comment="Months of programming experience",
    )

    # ── Step 11: Mathematics Assessment ──────────────────────────────────────
    math_is_favourite: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    math_daily_ok: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    math_career_ok: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)

    # ── Step 13: Personality ──────────────────────────────────────────────────
    personality_type: Mapped[Optional[str]] = mapped_column(
        String(30), nullable=True, index=True,
        comment="Introvert | Extrovert | Ambivert",
    )
    subject_type_preference: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 14: Learning Style ───────────────────────────────────────────────
    learning_styles: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 15: Hobbies ──────────────────────────────────────────────────────
    hobbies: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 16: Games ────────────────────────────────────────────────────────
    favourite_games: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 17: Financial Background ────────────────────────────────────────
    financial_status: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True,
        comment="Comfortable | Manageable | Need Scholarship | Tight Budget",
    )
    education_budget: Mapped[Optional[str]] = mapped_column(
        String(200), nullable=True,
        comment="Free-text amount e.g. 'PKR 500,000 total'",
    )

    # ── Step 18: Family Background ────────────────────────────────────────────
    parent_occupations: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    family_education: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    family_expectations: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    family_business: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Step 19: Career Goals ─────────────────────────────────────────────────
    goals_5yr: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    goals_10yr: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    goals_20yr: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Step 20: Lifestyle Preferences ───────────────────────────────────────
    lifestyle_preferences: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)

    # ── Step 21: Additional Notes ─────────────────────────────────────────────
    additional_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # -- Audit timestamps ----------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        CheckConstraint("age >= 10 AND age <= 60", name="ck_profiles_age_range"),
        CheckConstraint(
            "programming_interest >= 1 AND programming_interest <= 10",
            name="ck_profiles_programming_interest_range",
        ),
        CheckConstraint(
            "programming_experience >= 0",
            name="ck_profiles_programming_experience_non_negative",
        ),
        CheckConstraint(
            "secondary_marks >= 0 AND secondary_marks <= 100",
            name="ck_profiles_secondary_marks_range",
        ),
    )

    # -- Relationships -------------------------------------------------------
    session: Mapped["Session"] = relationship(
        "Session",
        back_populates="profile",
    )
    subject_performances: Mapped[List["SubjectPerformance"]] = relationship(
        "SubjectPerformance",
        back_populates="profile",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    interest_ratings: Mapped[List["InterestRating"]] = relationship(
        "InterestRating",
        back_populates="profile",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    communication_skills: Mapped[List["CommunicationSkill"]] = relationship(
        "CommunicationSkill",
        back_populates="profile",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return (
            f"<StudentProfile id={self.id} "
            f"name={self.name!r} "
            f"session_id={self.session_id}>"
        )


# ---------------------------------------------------------------------------
# 4. SUBJECT PERFORMANCE
#
# Purpose:
#   Normalised breakout of the subject_performance dict (step 5).
#   One row per subject per profile.  Enables analytics such as
#   "which subjects do students find hardest" or "correlate confidence
#   scores with AI-recommended career paths".
#
# Unique constraint:
#   (profile_id, subject_name) — a student cannot rate the same subject twice.
# ---------------------------------------------------------------------------

class SubjectPerformance(Base):
    __tablename__ = "subject_performances"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign key ---------------------------------------------------------
    profile_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # -- Data ----------------------------------------------------------------
    subject_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        index=True,
    )
    marks: Mapped[Optional[float]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="0.00–100.00; nullable if student skipped marks entry",
    )
    interest: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        comment="1–10; mirrors SubjectPerformanceEntry.interest in schemas.py",
    )
    difficulty: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    confidence: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    hours_per_week: Mapped[float] = mapped_column(
        Numeric(4, 1),
        nullable=False,
        comment="Hours per week the student spends on this subject",
    )

    # -- Audit ---------------------------------------------------------------
    recorded_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        UniqueConstraint(
            "profile_id", "subject_name",
            name="uq_subject_performances_profile_subject",
        ),
        CheckConstraint("interest >= 1 AND interest <= 10",   name="ck_sp_interest"),
        CheckConstraint("difficulty >= 1 AND difficulty <= 10", name="ck_sp_difficulty"),
        CheckConstraint("confidence >= 1 AND confidence <= 10", name="ck_sp_confidence"),
        CheckConstraint("hours_per_week >= 0",                 name="ck_sp_hours_non_negative"),
        CheckConstraint("marks >= 0 AND marks <= 100",         name="ck_sp_marks_range"),
    )

    # -- Relationship --------------------------------------------------------
    profile: Mapped["StudentProfile"] = relationship(
        "StudentProfile",
        back_populates="subject_performances",
    )

    def __repr__(self) -> str:
        return (
            f"<SubjectPerformance subject={self.subject_name!r} "
            f"marks={self.marks} interest={self.interest}>"
        )


# ---------------------------------------------------------------------------
# 5. INTEREST RATING
#
# Purpose:
#   Normalised breakout of the interest_ratings dict (step 9).
#   Currently 20 fields (INTEREST_FIELDS in config.py).  One row per field
#   per profile makes it trivial to add new interest categories and enables
#   cross-field analytics without schema migration.
#
# Unique constraint:
#   (profile_id, field_name) — one rating per interest field per student.
# ---------------------------------------------------------------------------

class InterestRating(Base):
    __tablename__ = "interest_ratings"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign key ---------------------------------------------------------
    profile_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # -- Data ----------------------------------------------------------------
    field_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="One of INTEREST_FIELDS from config.py e.g. 'Engineering', 'Law'",
    )
    rating: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        comment="1–10; mirrors InterestRatingsRequest validator in schemas.py",
    )

    # -- Audit ---------------------------------------------------------------
    recorded_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        UniqueConstraint(
            "profile_id", "field_name",
            name="uq_interest_ratings_profile_field",
        ),
        CheckConstraint(
            "rating >= 1 AND rating <= 10",
            name="ck_interest_ratings_rating_range",
        ),
    )

    # -- Relationship --------------------------------------------------------
    profile: Mapped["StudentProfile"] = relationship(
        "StudentProfile",
        back_populates="interest_ratings",
    )

    def __repr__(self) -> str:
        return f"<InterestRating field={self.field_name!r} rating={self.rating}>"


# ---------------------------------------------------------------------------
# 6. COMMUNICATION SKILL
#
# Purpose:
#   Normalised breakout of the communication_skills dict (step 12).
#   Eight skills defined in COMMUNICATION_SKILLS in config.py:
#   speaking, writing, listening, leadership, teamwork,
#   public_speaking, negotiation, presentation.
#   One row per skill per profile is analytically flexible and avoids
#   adding 8 separate columns to the profile table.
#
# Unique constraint:
#   (profile_id, skill_name) — one score per skill per student.
# ---------------------------------------------------------------------------

class CommunicationSkill(Base):
    __tablename__ = "communication_skills"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign key ---------------------------------------------------------
    profile_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("student_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # -- Data ----------------------------------------------------------------
    skill_name: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="One of COMMUNICATION_SKILLS from config.py",
    )
    score: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        comment="1–10; mirrors CommunicationSkillsRequest validator in schemas.py",
    )

    # -- Audit ---------------------------------------------------------------
    recorded_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        UniqueConstraint(
            "profile_id", "skill_name",
            name="uq_communication_skills_profile_skill",
        ),
        CheckConstraint(
            "score >= 1 AND score <= 10",
            name="ck_communication_skills_score_range",
        ),
    )

    # -- Relationship --------------------------------------------------------
    profile: Mapped["StudentProfile"] = relationship(
        "StudentProfile",
        back_populates="communication_skills",
    )

    def __repr__(self) -> str:
        return f"<CommunicationSkill skill={self.skill_name!r} score={self.score}>"


# ---------------------------------------------------------------------------
# 7. REPORT
#
# Purpose:
#   Each row is one AI-generated report.  A single session can produce
#   multiple report types (career, field_scope, field_comparison) and
#   multiple runs of the same type (regeneration).
#
#   session_id is nullable because field-scope and field-comparison reports
#   do not require a completed student session — they are general queries.
#
#   The status column enables async generation:
#     pending → generating → complete | failed
#   The API returns immediately and the frontend polls GET /reports/{id}/status.
#
#   generation_duration_ms captures how long the full AI pipeline took so
#   slow sections can be identified and optimised.
# ---------------------------------------------------------------------------

class Report(Base):
    __tablename__ = "reports"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign keys --------------------------------------------------------
    session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="NULL for field-scope / field-comparison reports (no session needed)",
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Denormalized for fast access-control checks without joining Session",
    )

    # -- Report identity -----------------------------------------------------
    report_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        index=True,
        comment="career | field_scope | field_comparison",
    )

    # -- Content -------------------------------------------------------------
    report_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full markdown output from the AI model",
    )
    pdf_path: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Relative filesystem path or S3 key — never expose directly to users",
    )

    # -- Generation lifecycle ------------------------------------------------
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="pending",
        index=True,
        comment="pending | generating | complete | failed",
    )
    generation_duration_ms: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Wall-clock ms for the entire AI generation pipeline",
    )

    # -- Audit timestamps ----------------------------------------------------
    generated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        nullable=True,
        index=True,
        comment="Scheduled cleanup — delete PDF and null report_text after this date",
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "report_type IN ('career', 'field_scope', 'field_comparison')",
            name="ck_reports_report_type_values",
        ),
        CheckConstraint(
            "status IN ('pending', 'generating', 'complete', 'failed')",
            name="ck_reports_status_values",
        ),
        CheckConstraint(
            "generation_duration_ms >= 0",
            name="ck_reports_duration_non_negative",
        ),
    )

    # -- Relationships -------------------------------------------------------
    session: Mapped[Optional["Session"]] = relationship(
        "Session",
        back_populates="reports",
    )
    user: Mapped[Optional["User"]] = relationship(
        "User",
        back_populates="reports",
    )
    sections: Mapped[List["ReportSection"]] = relationship(
        "ReportSection",
        back_populates="report",
        order_by="ReportSection.order_index",   # always retrieved in display order
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return (
            f"<Report id={self.id} "
            f"type={self.report_type!r} "
            f"status={self.status!r}>"
        )


# ---------------------------------------------------------------------------
# 8. REPORT SECTION
#
# Purpose:
#   Stores the output of each individual API call made during report
#   generation.  The existing report_generator.py makes multiple sequential
#   calls — one per section.  This table enables:
#
#     • Section-level resumability: if call 7 of 12 fails, only that section
#       is regenerated on retry.
#     • Observability: token_count per section surfaces which sections are
#       expensive.
#     • Future caching: if a field-scope section for "Medicine" already exists
#       and is recent enough, skip regenerating it.
#
# Unique constraint:
#   (report_id, section_key) — one text blob per named section per report.
#
# order_index:
#   The Report relationship orders by this column so sections are always
#   returned in the correct display sequence without ORDER BY in queries.
# ---------------------------------------------------------------------------

class ReportSection(Base):
    __tablename__ = "report_sections"

    # -- Primary key ---------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )

    # -- Foreign key ---------------------------------------------------------
    report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("reports.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # -- Data ----------------------------------------------------------------
    section_key: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Machine-readable section identifier e.g. 'career_matches', 'skill_gap'",
    )
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Raw text output returned by the AI for this section",
    )
    token_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Estimated via estimate_tokens() in api_client.py",
    )
    order_index: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        comment="Display ordering — Report.sections relationship sorts by this",
    )

    # -- Audit ---------------------------------------------------------------
    generated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=func.now(),
    )

    # -- Constraints ---------------------------------------------------------
    __table_args__ = (
        UniqueConstraint(
            "report_id", "section_key",
            name="uq_report_sections_report_key",
        ),
        CheckConstraint(
            "token_count >= 0",
            name="ck_report_sections_token_count_non_negative",
        ),
        CheckConstraint(
            "order_index >= 0",
            name="ck_report_sections_order_index_non_negative",
        ),
    )

    # -- Relationship --------------------------------------------------------
    report: Mapped["Report"] = relationship(
        "Report",
        back_populates="sections",
    )

    def __repr__(self) -> str:
        return (
            f"<ReportSection key={self.section_key!r} "
            f"order={self.order_index} "
            f"tokens={self.token_count}>"
        )