"""Initial models

Revision ID: c43a6a8f34a9
Revises: 
Create Date: 2026-07-16 17:42:09.306344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c43a6a8f34a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Surrogate PK — never expose sequential IDs in public APIs'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Login key — RFC 5321 max length is 320 chars'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='bcrypt hash; NULL for OAuth-only accounts'),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='student', nullable=False, comment='student | counsellor | admin'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-disable without deletion'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='Email verification gate'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Updated on successful authentication'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False, comment='SES001 format; unique; used in all existing API URLs'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL = anonymous / guest session'),
    sa.Column('current_step', sa.SmallInteger(), server_default='1', nullable=False, comment='1–21; incremented by each /steps/* endpoint'),
    sa.Column('steps_completed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Ordered list of step numbers that have been submitted'),
    sa.Column('collection_complete', sa.Boolean(), server_default='false', nullable=False, comment='Set true after step 21 is submitted'),
    sa.Column('report_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False, comment='active | completed | abandoned | expired'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Indexed for session history sorted by recency'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='TTL; cleanup job deletes rows where expires_at < now()'),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned', 'expired')", name='ck_sessions_status_values'),
    sa.CheckConstraint('current_step >= 1 AND current_step <= 21', name='ck_sessions_current_step_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_code'), 'sessions', ['session_code'], unique=True)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='NULL for field-scope / field-comparison reports (no session needed)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Denormalized for fast access-control checks without joining Session'),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='career | field_scope | field_comparison'),
    sa.Column('report_text', sa.Text(), nullable=False, comment='Full markdown output from the AI model'),
    sa.Column('pdf_path', sa.String(length=500), nullable=True, comment='Relative filesystem path or S3 key — never expose directly to users'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='pending | generating | complete | failed'),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=True, comment='Wall-clock ms for the entire AI generation pipeline'),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Scheduled cleanup — delete PDF and null report_text after this date'),
    sa.CheckConstraint("report_type IN ('career', 'field_scope', 'field_comparison')", name='ck_reports_report_type_values'),
    sa.CheckConstraint("status IN ('pending', 'generating', 'complete', 'failed')", name='ck_reports_status_values'),
    sa.CheckConstraint('generation_duration_ms >= 0', name='ck_reports_duration_non_negative'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_expires_at'), 'reports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='One profile per session — UNIQUE FK enforces 1:1'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Denormalized for fast user-profile lookup without joining Session'),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='Validated 10–60 by Pydantic; CHECK enforces at DB level'),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('native_language', sa.String(length=100), nullable=True),
    sa.Column('education_language', sa.String(length=100), nullable=True),
    sa.Column('secondary_system', sa.String(length=50), nullable=True, comment='Matric | O-Level | Other'),
    sa.Column('secondary_year', sa.SmallInteger(), nullable=True),
    sa.Column('secondary_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='e.g. ["Math", "Physics", "Chemistry"]'),
    sa.Column('secondary_marks', sa.Numeric(precision=5, scale=2), nullable=True, comment='0.00–100.00'),
    sa.Column('secondary_grade', sa.String(length=10), nullable=True),
    sa.Column('secondary_completed', sa.Boolean(), nullable=True),
    sa.Column('higher_system', sa.String(length=50), nullable=True, comment='FSc | A-Level | Other'),
    sa.Column('higher_year', sa.SmallInteger(), nullable=True),
    sa.Column('higher_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('higher_subject_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='e.g. {"Computer Science": "95%", "Math": "90%"}'),
    sa.Column('higher_completed', sa.Boolean(), nullable=True),
    sa.Column('favourite_subject', sa.String(length=200), nullable=True),
    sa.Column('favourite_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_degree_plan', sa.Text(), nullable=True),
    sa.Column('study_country', sa.String(length=100), nullable=True),
    sa.Column('work_country', sa.String(length=100), nullable=True),
    sa.Column('has_programmed', sa.Boolean(), nullable=True),
    sa.Column('programming_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('programming_interest', sa.SmallInteger(), nullable=True),
    sa.Column('programming_experience', sa.SmallInteger(), nullable=True, comment='Months of programming experience'),
    sa.Column('math_is_favourite', sa.Boolean(), nullable=True),
    sa.Column('math_daily_ok', sa.Boolean(), nullable=True),
    sa.Column('math_career_ok', sa.Boolean(), nullable=True),
    sa.Column('personality_type', sa.String(length=30), nullable=True, comment='Introvert | Extrovert | Ambivert'),
    sa.Column('subject_type_preference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hobbies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favourite_games', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_status', sa.String(length=50), nullable=True, comment='Comfortable | Manageable | Need Scholarship | Tight Budget'),
    sa.Column('education_budget', sa.String(length=200), nullable=True, comment="Free-text amount e.g. 'PKR 500,000 total'"),
    sa.Column('parent_occupations', sa.Text(), nullable=True),
    sa.Column('family_education', sa.Text(), nullable=True),
    sa.Column('family_expectations', sa.Text(), nullable=True),
    sa.Column('family_business', sa.Text(), nullable=True),
    sa.Column('goals_5yr', sa.Text(), nullable=True),
    sa.Column('goals_10yr', sa.Text(), nullable=True),
    sa.Column('goals_20yr', sa.Text(), nullable=True),
    sa.Column('lifestyle_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age >= 10 AND age <= 60', name='ck_profiles_age_range'),
    sa.CheckConstraint('programming_experience >= 0', name='ck_profiles_programming_experience_non_negative'),
    sa.CheckConstraint('programming_interest >= 1 AND programming_interest <= 10', name='ck_profiles_programming_interest_range'),
    sa.CheckConstraint('secondary_marks >= 0 AND secondary_marks <= 100', name='ck_profiles_secondary_marks_range'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_country'), 'student_profiles', ['country'], unique=False)
    op.create_index(op.f('ix_student_profiles_personality_type'), 'student_profiles', ['personality_type'], unique=False)
    op.create_index(op.f('ix_student_profiles_session_id'), 'student_profiles', ['session_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_study_country'), 'student_profiles', ['study_country'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=False)
    op.create_table('communication_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=50), nullable=False, comment='One of COMMUNICATION_SKILLS from config.py'),
    sa.Column('score', sa.SmallInteger(), nullable=False, comment='1–10; mirrors CommunicationSkillsRequest validator in schemas.py'),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 10', name='ck_communication_skills_score_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_name', name='uq_communication_skills_profile_skill')
    )
    op.create_index(op.f('ix_communication_skills_profile_id'), 'communication_skills', ['profile_id'], unique=False)
    op.create_index(op.f('ix_communication_skills_skill_name'), 'communication_skills', ['skill_name'], unique=False)
    op.create_table('interest_ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False, comment="One of INTEREST_FIELDS from config.py e.g. 'Engineering', 'Law'"),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='1–10; mirrors InterestRatingsRequest validator in schemas.py'),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_interest_ratings_rating_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'field_name', name='uq_interest_ratings_profile_field')
    )
    op.create_index(op.f('ix_interest_ratings_field_name'), 'interest_ratings', ['field_name'], unique=False)
    op.create_index(op.f('ix_interest_ratings_profile_id'), 'interest_ratings', ['profile_id'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False, comment="Machine-readable section identifier e.g. 'career_matches', 'skill_gap'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Raw text output returned by the AI for this section'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Estimated via estimate_tokens() in api_client.py'),
    sa.Column('order_index', sa.SmallInteger(), nullable=False, comment='Display ordering — Report.sections relationship sorts by this'),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_report_sections_order_index_non_negative'),
    sa.CheckConstraint('token_count >= 0', name='ck_report_sections_token_count_non_negative'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'section_key', name='uq_report_sections_report_key')
    )
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    op.create_table('subject_performances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('marks', sa.Numeric(precision=5, scale=2), nullable=True, comment='0.00–100.00; nullable if student skipped marks entry'),
    sa.Column('interest', sa.SmallInteger(), nullable=False, comment='1–10; mirrors SubjectPerformanceEntry.interest in schemas.py'),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('hours_per_week', sa.Numeric(precision=4, scale=1), nullable=False, comment='Hours per week the student spends on this subject'),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 1 AND confidence <= 10', name='ck_sp_confidence'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 10', name='ck_sp_difficulty'),
    sa.CheckConstraint('hours_per_week >= 0', name='ck_sp_hours_non_negative'),
    sa.CheckConstraint('interest >= 1 AND interest <= 10', name='ck_sp_interest'),
    sa.CheckConstraint('marks >= 0 AND marks <= 100', name='ck_sp_marks_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'subject_name', name='uq_subject_performances_profile_subject')
    )
    op.create_index(op.f('ix_subject_performances_profile_id'), 'subject_performances', ['profile_id'], unique=False)
    op.create_index(op.f('ix_subject_performances_subject_name'), 'subject_performances', ['subject_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_performances_subject_name'), table_name='subject_performances')
    op.drop_index(op.f('ix_subject_performances_profile_id'), table_name='subject_performances')
    op.drop_table('subject_performances')
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_interest_ratings_profile_id'), table_name='interest_ratings')
    op.drop_index(op.f('ix_interest_ratings_field_name'), table_name='interest_ratings')
    op.drop_table('interest_ratings')
    op.drop_index(op.f('ix_communication_skills_skill_name'), table_name='communication_skills')
    op.drop_index(op.f('ix_communication_skills_profile_id'), table_name='communication_skills')
    op.drop_table('communication_skills')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_study_country'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_session_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_personality_type'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_country'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_expires_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_code'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###